version: '3.9'

services: 
  database:
    image: mysql
    container_name: smart-table
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: 'smart_table'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'